{% set version = "2.2.0" %}


package:
  name: tensorflow
  version: {{ version }}

source:
  fn: {{ fn }}
  url: https://github.com/tensorflow/tensorflow/archive/v{{ version }}.tar.gz  # [linux]
  sha256: 69cd836f87b8c53506c4f706f655d423270f5a563b76dc1cfa60fbc3184185a3  # [linux]

  patches:
    #- patches/0001-add-rt-to-linkopts.patch                                     # [linux]
    #- patches/0002-stable-image-rotate-test.patch                               # [linux]
    - patches/0003-relax-tolerence-in-special_math_test.patch                   # [linux]
    - patches/0004-skip-read-only-debugger_cli_common-test.patch                # [linux]
    #- patches/0005-fix-lookup_ops-test.patch                                    # [linux]
    - patches/0006-relax-precision-in-matrix_log_op_test.patch                  # [linux]
    #- patches/0007-Add-init-symbol-names-prefixed-with-an-underscore.patch      # [osx]
    #- patches/0008-Add-alternate-clock_gettime-implementation-for-macOS.patch   # [osx]
    - patches/unbundle_llvm.patch                                               # [linux]

build:
  number: 0
  skip: True  # [not x86_64]

requirements:
  build:
    - {{ compiler('c') }}       # [linux]
    - {{ compiler('cxx') }}     # [linux]
    #- bazel ==2.0.0   # [linux]
    - nasm                      # [linux]
    - swig                      # [linux]
  host:
    # conda build requirements
    - python
    - pip
    #- setuptools <=39.1.0
    # requirements specified by the package itself
    - absl-py >=0.1.6
    - astor >=0.6.0
    - gast >=0.2.0
    - keras-applications >=1.0.6
    - keras-preprocessing >=1.0.5
    - llvmdev >=8.0.0,<9.0.0    # [linux]
    - zlib                      # [linux]
    - libpng                    # [linux]
    - libcurl                   # [linux]
    - unzip  # [linux]
    - zip  # [linux]
    - openjdk >=8  # [linux]
    - nsync  # [linux]
    - numpy >=1.16.1
    - six >=1.10.0
    - protobuf >=3.6.1
    - termcolor >=1.1.0
    - grpcio >=1.8.6
    - wheel >=0.26              # [linux]
    - tensorflow-estimator >=2.2.0,<2.3.0a0
  run:
    - {{ pin_subpackage('tensorflow-base', exact=True) }}

outputs:
  - name: tensorflow-base
    build:
      entry_points:
        - toco_from_protos = tensorflow.lite.toco.python.toco_from_protos:main
        - tflite_convert = tensorflow.lite.python.tflite_convert:main
        - toco = tensorflow.lite.python.tflite_convert:main
        - saved_model_cli = tensorflow.python.tools.saved_model_cli:main
        # The tensorboard package adds this entry point.
        # - tensorboard = tensorboard.main:run_main
        - tf_upgrade_v2 = tensorflow.tools.compatibility.tf_upgrade_v2_main:main
        - estimator_ckpt_converter = tensorflow_estimator.python.estimator.tools.checkpoint_converter:main
    requirements:
      # build requirements needs to pick up the compiler run_exports
      build:
        - {{ compiler('c') }}       # [linux]
        - {{ compiler('cxx') }}     # [linux]
      host:
        # conda build requirements
        - python
        - pip
        # requirements specified by the package itself
        - absl-py >=0.1.6
        - astor >=0.6.0
        - astunparse
        - gast >=0.2.0
        - google-pasta
        - h5py
        - keras-preprocessing >=1.0.5
        - numpy >=1.16.1
        - six >=1.10.0
        - protobuf >=3.6.1
        - termcolor >=1.1.0
        - grpcio >=1.8.6
        - wheel >=0.26              # [unix]
        - tensorflow-estimator >=2.2.0,<2.3.0a0
        - zlib  # [linux]
        - libpng  # [linux]
        - libcurl  # [linux]
      run:
        - python
        - absl-py >=0.1.6
        - astor >=0.6.0
        - astunparse
        - gast >=0.2.0
        - google-pasta
        - h5py
        - opt_einsum
        - keras-preprocessing >=1.0.5
        - {{ pin_compatible('numpy') }}
        - scipy
        - six >=1.10.0
        - protobuf >=3.6.1
        - termcolor >=1.1.0
        - grpcio >=1.8.6
        - tensorflow-estimator >=2.2.0,<2.3.0a0
        - tensorboard >=2.2.0,<2.3.0a0
    test:
      imports:
        - tensorflow
      commands:
        - freeze_graph --help
        - saved_model_cli --help
        - tflite_convert --help  # [not win]
        - toco_from_protos --help  # [not win]
        - toco --help  # [not win]

  - name: libtensorflow
    script: cp_libtensorflow.sh  # [unix]
    build:
      skip: true  # [not linux]
    requirements:
      # build requirements needs to pick up the compiler run_exports
      build:
        - {{ compiler('c') }}       # [linux]
        - {{ compiler('cxx') }}     # [linux]
      # host requirements to pick up run_exports
      host:
        - libcurl  # [linux]
        - zlib  # [linux]

    test:
      files:
        - test_c.c
      requires:
        - {{ compiler('c') }}
      commands:
        - test -f $PREFIX/lib/libtensorflow.so  # [not win]
        - $CC -o test_c -L${PREFIX}/lib/ -ltensorflow -I${PREFIX}/include/ test_c.c && ./test_c  # [not win]

  - name: libtensorflow_cc
    script: cp_libtensorflow_cc.sh  # [unix]
    build:
      skip: true  # [not linux]
    requirements:
      # build requirements needs to pick up the compiler run_exports
      build:
        - {{ compiler('c') }}       # [linux]
        - {{ compiler('cxx') }}     # [linux]
      # host requirements to pick up run_exports
      host:
        - libcurl  # [linux]
        - zlib  # [linux]
      run:
        - libprotobuf >=3.6.1,<3.7
        - nsync
    test:
      files:
        - test_cc.cc
      requires:
        - {{ compiler('cxx') }}
      commands:
        - test -f $PREFIX/lib/libtensorflow_cc.so  # [not win]
        - $CXX -std=c++11 -o test_cc -L${PREFIX}/lib/ -ltensorflow_cc -ltensorflow_framework -lrt -I${PREFIX}/include/ test_cc.cc && ./test_cc  # [not win]

about:
  home: http://tensorflow.org/
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: TensorFlow is an open source machine learning framework for everyone.
  description: |
    TensorFlow provides multiple APIs.The lowest level API, TensorFlow Core
    provides you with complete programming control.
    Base package contains only tensorflow, not tensorflow-tensorboard.
  dev_url: https://github.com/tensorflow/tensorflow
  doc_url: https://www.tensorflow.org/get_started/get_started
  doc_source_url: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/docs_src

extra:
  recipe-maintainers:
    - waitingkuo
    - ghego
    - hajapy
    - gilbertfrancois
    - farhantejani
    - njzjz
    - jschueller
